import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Void Archives",
  description: "Generated by create next app",
  // icons: {
  //   icon: [
  //     {
  //       media: '(prefers-color-scheme: light)',
  //       url: "/imgs/web_icon.png",
  //       href: "/imgs/web_icon.png",
  //     },
  //     {
  //       media: '(prefers-color-scheme: dark)',
  //       url: "/imgs/web_icon.png",
  //       href: "/imgs/web_icon.png",
  //     }
  //   ]
  // }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="/imgs/web_icon.png" href="/imgs/web_icon.png" />
      </head>
      <body className={`${inter.className} myscrollbar`}>
        {children}
      </body>
    </html>
  );
}
